# Generated by Django 5.1.2 on 2024-10-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cd_customer', models.AutoField(primary_key=True, serialize=False)),
                ('nm_customer', models.CharField(max_length=90)),
                ('nr_cpf_customer', models.CharField(max_length=11)),
                ('dt_customer', models.DateField()),
                ('ds_email_customer', models.TextField()),
            ],
        ),
    ]
