# Generated by Django 5.1.2 on 2024-10-12 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('cd_visit', models.AutoField(primary_key=True, serialize=False)),
                ('dt_visit_customer', models.DateField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
