# Generated by Django 5.1.2 on 2024-10-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('cd_employee', models.AutoField(primary_key=True, serialize=False)),
                ('nm_employee', models.CharField(max_length=90)),
                ('ds_email_employee', models.TextField()),
                ('ds_pass_employee', models.CharField()),
                ('nm_position', models.CharField(max_length=90)),
            ],
        ),
    ]
